# Dependencies
markdown:         kramdown
gems:             [jekyll-paginate]

# Setup
title:            Designs By Fiona
tagline:          'Designs By Fiona'
description:      'Designs By Fiona'
url:              http://byfiona.ca
baseurl:          "/"

author:
  name:           'Fiona Mascarenhas'
  url:            https://twitter.com/_fionaaa

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
